### ISSUE TITLE
Updating redactor plugin in Craft 3 removes its files

### ISSUE THREAD

**Issue by empcraftdev** [simplicate-web/redactor-link-styles#1]
Hi Steve,
Thank you for making this plugin. I installed it in a Craft CMS version 3 project by adding its files to plugin's directory. It works well but the files will remove whenever I update redactor from admin panel. 
Is it possible for you to add it as a Craft 3 plugin, like https://plugins.craftcms.com/redactor-custom-styles

Regards
Karan

**Comment by stevecomrie** [comment]
Hey Karan,

What directory are you saving the files into?

These should be saved in sub folder of the same place your local craft configuration is saved: i.e. `cms/config/redactor/plugins`
